### ISSUE TITLE
Constant Error

### ISSUE THREAD

**Issue by snowulow** [Yoshiyuka/TradeSkillMaster#1]
Addon: TradeSkillMaster
Message:  ...ns\TradeSkillMaster\Libs\AceComm-3.0\AceComm-3.0.lua:245: attempt to call upvalue 'Ambiguate' (a nil value)
Date: 11/27/15 21:15:00
Client: 3.3.5
Locale: deDE
Stack:

[string "_:OnLoad"]:4: <[string "_:OnLoad"]:1>
TSM\Libs\AceComm-3.0\AceComm-3.0.lua:245: AceComm-3.0.lua:243
TSM Stack:

Local Variables:

TSM Event Log:

Addons:
    Altoholic_Achievements (r90)
    AtlasLoot (v5.11.04)
    Auc-Advanced (5.8.4723 (CreepyKangaroo))
    AuctionProfitMaster ()
    Auctionator (2.6.3)
    Bagnon (2.13.2b)
    Bartender4 (4.4.2)
    BasicChatMods (v3.51)
    BeanCounter (5.8.4723 (CreepyKangaroo))
    Btex (2.9.2)
    ButtonFacade (r333)
    ClassLoot (v1.7.2)
    ClassTimer (2.3.30300.1)
    DataStore (r26)
    DXE (v503-2-gb605121)
    Enchantrix (5.8.4723 (CreepyKangaroo))
    Enchantrix-Barker (5.8.4723 (CreepyKangaroo))
    Gag_DefaultSoundPack ()
    Gag_ExampleSoundPack ()
    Gatherer (3.1.16)
    Gatherer_HUD (3.1.16)
    GathererDB_Wowhead (1.0.2009-02-18)
    GearScoreLite (3x04)
    Gladius (v1.0.3)
    Grid2 (r523)
    Informant (5.8.4723 (CreepyKangaroo))
    Ace2 (r1098)
    Ace3 (Release-r960)
    CallbackHandler-1.0 (1.0.6)
    LibStub ()
    LilSparkysWorkshop (r94)
    MailOpener (v1.2.5)
    Minimalist (r95)
    MoveAnything (11.b2)
    MrPlow (v10.2.11-Beta)
    NiceDamage (20400)
    Omen (v3.0.8)
    OmniCC (3.0.4)
    OmniCC_Config ()
    PallyPower (v3.2.4-release)
    PhoenixStyleMod_Coliseum ()
    PhoenixStyleMod_Icecrown ()
    PhoenixStyleMod_Ulduar ()
    PowerAuras (2.6.2J)
    Prat-3.0 (3.3.26)
    Quartz (r23-release)
    Quartz_Buff (r23-release)
    Quartz_Flight (r23-release)
    Quartz_Focus (r23-release)
    Quartz_GCD (r23-release)
    Quartz_Interrupt (r23-release)
    Quartz_Latency (r23-release)
    Quartz_Mirror (r23-release)
    Quartz_Pet (r23-release)
    Quartz_Player (r23-release)
    Quartz_Range (r23-release)
    Quartz_Swing (r23-release)
    Quartz_Target (r23-release)
    Quartz_Timer (r23-release)
    Quartz_Tradeskill (r23-release)
    RatingBuster (1.4.8)
    Recount (v3.2a release)
    sct_options (v6.42)
    sctd_options (v3.3)
    SkadaAbsorbs (r301)
    SlideBar (5.8.4723 (CreepyKangaroo))
    Stubby (5.8.4723 (CreepyKangaroo))
    !Swatter (5.8.4723 (CreepyKangaroo))
    TidyPlates (5.13.3 (R39))
    TipTacItemRef (10.02.27)
    TitanAmmo (4.3.8.30300)
    TweakWoW (2.9.6b)
    TSM (v2.8)
    TSM_Accounting (v2.3)
    TSM_AuctionDB (v2.3.10)
    TSM_Auctioning (v2.3.3)
    TSM_Crafting (v2.5)
    TSM_Destroying (v2.1.1)
    TSM_ItemTracker (v2.0.8)
    TSM_Mailing (v2.2.1)
    TSM_Shopping (v2.3.5)
    pError (30200.3-Beta)
    DBM-GUI ()

**Comment by Yoshiyuka** [comment]
This error was caused by the Ace libraries being a newer version than expected. Libraries were rolled back to older versions to be compatible with the 3.3.5a client.
