### ISSUE TITLE
TSM Desktop app Compatibility

### ISSUE THREAD

**Issue by NicciZar** [Yoshiyuka/TradeSkillMaster#13]
Is it possible to use the **TSM Deskop** APP (Windows) when playing on **unofficial / private** servers? 
It seems like there is no way to change the Server Address for that app (or I didnt find the option for that)

Thank you

**Comment by Aphroditus-Netherwing** [comment]
It is not you need to manually scan the ah about twice a day for about 2 weeks to get a baseline for market value.

**Comment by NicciZar** [comment]
Thank you my issue / question has now been resolved.

Best regards
